defaults:
  run:
    working-directory: aspnet

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: dotnet restore
      - run: dotnet build

  test:
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: dotnet test
  
  analyze:
    needs: [build, test]
    runs-on: ubuntu-20.04
    env:
      SONARCLOUD_TOKEN: ${{ secrets.michaelToken }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - run: dotnet tool install --global dotnet-sonarscanner
      - run: |
          dotnet sonarscanner begin /k:'mlaba49_demo-git' /o:'mlaba49' /d:sonar.host.url='https://sonarcloud.io/' /d:sonar.login=$SONARCLOUD_TOKEN
          dotnet build
          dotnet test
          dotnet sonarscanner end /d:sonar.login=$SONARCLOUD_TOKEN
  
  pack:
    needs:
      - build
      - test
    runs-on: ubuntu-20.04
    env:
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
    steps:
      - uses: actions/checkout@v2
      - run: echo DOCKER_TOKEN | docker login -u DOCKER_USER --password-stdin
      - run: docker image build -f ../dockerfile -t dockerdemo ../
      - run: docker image tag dockerdemo mlaba49/dockerdemo
      - run: docker image push mlaba49/dockerdemo
      - run: docker logout

on: push